---
title: "Drug Data Cleaning & Exploration"
author: "Suman Tripathy, Amanda Steigman"
date: "11/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(vcd)
library(forcats)
library(scales)
library(dplyr)
library(plyr)
library(tidyverse)
```

```{r}
load("35509-0001-Data.rda")
drug_study <- da35509.0001
```

```{r 5load}
# Examine the overall survey demographic
summary(drug_study$IRSEX)
summary(drug_study$AGE2)
summary(drug_study$INCOME)
summary(drug_study$EDUCCAT2)
summary(drug_study$NEWRACE2)

# Proportion of Oxycontin users in data
drug_study$OXYEVER <- ifelse(drug_study$OXYFLAG == "(1) Ever Used (IROXYRC = 1-3)","yes","no")
print(sum(drug_study$OXYEVER=="yes")/nrow(drug_study))
```

```{r 5b}
# clean data for graph
drug_study_sub <- drug_study[drug_study$OXYEVER=="yes",]
drug_study_sub$Sex <- ifelse(drug_study_sub$IRSEX == "(1) Male","Male","Female")
drug_study_sub$INCOME <- as.character(drug_study_sub$INCOME)

drug_study_sub$INCOME = revalue(drug_study_sub$INCOME, c("(1) Less than $20,000"="<$20,000", "(2) $20,000 - $49,999"="$20,000 - $49,999", "(3) $50,000 - $74,999"="$50,000 - $74,999", "(4) $75,000 or More"=">$75,000"))

drug_study_sub$Sex <- as.factor(drug_study_sub$Sex)
drug_study_sub$Income_Brackets <- as.factor(drug_study_sub$INCOME)
drug_study_sub$Income <- fct_relevel(drug_study_sub$Income_Brackets,">$75,000",after=3)
mosaic(Income ~ Sex,
       data = drug_study_sub, 
       direction = c("v", "h"),
       labeling_args = list(rot_labels = c(0, 0, 0, 0), offset_varnames = c(left = 6), offset_labels = c(left = 2.6)),
       main = "Sex and Income of Oxycontin Users")
```


```{r}
impt interesting columns we may want to look at
HEREVER - Ever used heroin
HERAGE - age when first used heroin
HERREC - time since last used heroin
HERYRTOT - total num of days using heroin in past year
HERFLAG	HEROIN - EVER USED
HERYR	HEROIN - PAST YEAR USE
HERMON	HEROIN - PAST MONTH USE

ANLFLAG	PAIN RELIEVERS - EVER USED
ANLYR	PAIN RELIEVERS - PAST YEAR USE
ANLMON	PAIN RELIEVERS - PAST MONTH USE
DARVTYLC - EVER USED DARVOCET, DARVON, OR TYLENOL W/ CODEINE
PERCTYLX - EVER USED PERCOCET, PERCODAN, OR TYLOX
VICOLOR	- EVER USED VICODIN, LORTAB, OR LORCET
ANLCARD	- EVER USED PAIN RELIEVER BELOW RED LINE ON CARD A
CODEINE	- EVER USED CODEINE NONMEDICALLY
DEMEROL	- EVER USED DEMEROL NONMEDICALLY
DILAUD	- EVER USED DILAUDID NONMEDICALLY
FIORICET	- EVER USED FIORICET NONMEDICALLY
FIORINAL	- EVER USED FIORINAL NONMEDICALLY
HYDROCOD -	EVER USED HYDROCODONE NONMEDICALLY
METHDON	- EVER USED METHADONE NONMEDICALLY
MORPHINE	- EVER USED MORPHINE NONMEDICALLY
OXYCONTN	- EVER USED OXYCONTIN NONMEDICALLY
PHENCOD	- EVER USED PHENAPHEN WITH CODEINE NONMEDICALLY
PROPOXY	- EVER USED PROPOXYPHENE NONMEDICALLY
SK65A	- EVER USED SK65 NONMEDICALLY
STADOL	- EVER USED STADOL NONMEDICALLY
TALACEN	- EVER USED TALACEN NONMEDICALLY
TALWIN	- EVER USED TALWIN NONMEDICALLY
TALWINNX -	EVER USED TALWINNX NONMEDICALLY
TRAMADOL -	EVER USED TRAMADOL NONMEDICALLY
ULTRAM - EVER USED ULTRAM NONMEDICALLY
ANLNOLST - EVER USED ANY OTHER PAIN RELIEVER NONMEDICALLY
ANALAGE - AGE WHEN FIRST USED PAIN RELIEVERS NONMEDICALLY
OXYCAGE	- AGE WHEN FIRST USED OXYCONTIN NONMEDICALLY
OXYCYFU	- YEAR OF FIRST OXYCONTIN USE - RECODE
OXYCMFU	- MONTH OF FIRST OXYCONTIN USE - RECODE
OXYCREC -	TIME SINCE LAST USED OXYCONTIN NONMEDICALLY
OXYYRTOT	- TOTAL NUM DAYS USED OXYCONTIN PAST 12 MONTHS
OXTOTFG	- TRIMMING INDICATOR FOR OXYYRTOT
OXFQFLG	- TRIMMED OXYYRTOT IF R USED < 12 MOS
OXBSTWAY	- EASIEST WAY TO TELL US NUM DAYS USED OXYCONTIN
OXDAYPYR	- NUM DAYS USED OXYCONTIN 'NM' PAST 12 MONTHS
OXDAYPMO	- NUM DAYS PER MO USED OXYCONTIN 'NM' PAST 12 MOS
OXDAYPWK	- NUM DAYS PER WK USED OXYCONTIN 'NM' PAST 12 MOS
IRANLFY	PAIN RELIEVER FREQ PAST YEAR - IMPUTATION REVISED
IIANLFY	PAIN RELIEVER FREQ PAST YEAR - IMP INDICATOR
II2ANLFY	PAIN RELIEVER FREQ PAST YR-DETAILED IMP INDICATOR
IRHERFM	HEROIN FREQUENCY PAST MONTH - IMPUTATION REVISED
IIHERFM	HEROIN FREQUENCY PAST MONTH - IMPUTATION INDICATOR
II2HERFM	HEROIN FREQ PAST MONTH - DETAILED IMP INDICATOR

ANLRX1D2	GOT ONE+ RX FOR ANL FROM JUST ONE DOCTOR - PST MON
ANLRXDS2	GOT RX FOR ANL FROM 2 OR MORE DOCTORS - PST MON
ANLRXFK2	WROTE FAKE PRESCRIPTION FOR ANL - PST MON
ANLSTOL2	STOLE ANL FROM DRS OFF/CLIN/HOSP/PHARM - PST MON
ANLFRFE2	GOT ANL FROM A FRIEND/RELATIVE FOR FREE - PST MON
ANLFRBY2	BOUGHT ANL FROM A FRIEND OR RELATIVE - PST MON
ANLFRTK2	TOOK ANL FROM FRND/RELATIVE WITHOUT ASK - PST MON
ANLDEAL2	BOUGHT ANL FROM DRUG DEALR/OTH STRANGER - PST MON
ANLINET2	BOUGHT ANL ON THE INTERNET - PST MON
ANLOTHW2	GOT ANL IN SOME OTHER WAY - PST MON
GOVTPROG	PARTICIPATED IN ONE OR MORE GOVT ASSIST PROGRAMS
INCOME	TOTAL FAMILY INCOME RECODE
POVERTY2	POVERTY LEVEL (% OF US CENSUS POVERTY THRESHOLD)

BOOKED	EVER ARRESTED AND BOOKED FOR BREAKING THE LAW
NOBOOKY2	# TIMES ARRESTED AND BOOKED PAST 12 MONTHS
BKMVTHFT	ARRSTD & BOOKED FOR MOT VEH THEFT PAST 12 MONTHS
BKLARCNY	ARRSTD & BOOKED FOR LARCENY/THEFT PAST 12 MONTHS
BKBURGL	ARRSTD & BOOKED FOR BURGLARY/B & E PAST 12 MOS
BKSRVIOL	ARRSTD & BOOKED SERIOUS VIOL OFFENSE PST 12 MOS
BKSMASLT	ARRSTD & BOOKED FOR OTHER ASSAULT PAST 12 MONTHS
BKROB	ARRSTD & BOOKED FOR ROBBERY PAST 12 MONTHS
BKARSON	ARRSTD & BOOKED FOR ARSON PAST 12 MONTHS
BKDRVINF	ARRSTD & BOOKED FOR DUI PAST 12 MONTHS
BKDRUNK	ARRSTD & BOOKED FOR DRUNKENNESS PAST 12 MONTHS
BKPOSTOB	ARRSTD & BOOKED FOR POSSES OF TOB PAST 12 MOS
BKDRUG	ARRSTD & BOOKED FOR POSSES/SALE DRUGS PAST 12 MOS
BKSEXNR	ARRSTD & BOOKED SEX OFFENSE EXCL RAPE PST 12 MOS
BKFRAUD	ARRSTD & BOOKED FOR FRAUD/STOL GOODS PAST 12 MOS
BKOTH	ARRSTD & BOOKED FOR SOME OTHER OFF PAST 12 MOS
```

```{r}
drug_study_demographic = drug_study_sub %>% 
  select(INCOME, IRSEX, EMPSTATY, AGE2, EDUCCAT2, NEWRACE2)

drug_study_demographic$SEX = revalue(drug_study_demographic$IRSEX, c("(1) Male"="Male", "(2) Female"="Female"))
drug_study_demographic$EMPSTATY = revalue(drug_study_demographic$EMPSTATY, c("(1) Employed full time"="Employed full time", "(2) Employed part time"="Employed part time", "(3) Unemployed"="Unemployed", "(4) Other (incl. not in labor force)"="Other (incl. not in labor force)"))
drug_study_demographic$EDUCCAT2 = revalue(drug_study_demographic$EDUCCAT2, c("(1) Less than high school (IREDUC2<=7 and AGE2>=7)"="Less than high school", "(2) High school graduate (IREDUC2=8 and AGE2>=7)"="High school graduate", "(3) Some college (IREDUC2=9-10 and AGE2>=7)"="Some college", "(4) College graduate (IREDUC2=11 and AGE2>=7)"="College Graduate", "(5) 12 to 17 year olds (AGE2<=6)"="Less than high school"))
```

```{r}
library(mi)
x <- missing_data.frame(drug_study_demographic)
image(x)
```

```{r}
drug_study_demographic$INCOME <- fct_relevel(drug_study_demographic$INCOME,">$75,000",after=3)
mosaic(INCOME ~ SEX, 
       direction=c('v','h'), 
       labeling_args = list(rot_labels = c(0, 0, 0, 0), 
                            offset_varnames = c(left = 6), 
                            offset_labels = c(left = 2.6)),
       gp = grid::gpar(fill=c('#CCCCFF', '#CC99FF', '#9966CC', '#663399')),
       main = "Sex and Income of Oxycontin Users",
       drug_study_demographic)
```
```{r}
summary(drug_study_demographic$EDUCCAT2)
```


```{r}
mosaic(EDUCCAT2 ~ EMPSTATY, 
       direction=c('v','h'), 
       labeling_args = list(rot_labels = c(45, 0, 0, 0), 
                            offset_varnames = c(left = 6), 
                            offset_labels = c(left = 2.6)),
       gp = grid::gpar(fill=c('#CCCCFF', '#CC99FF', '#9966CC', '#663399')),
       main = "Sex and Income of Oxycontin Users",
       drug_study_demographic)
# Out of Oxycontin users, definitely a much smaller portion are college graduates. 88% of users had some college or less (obviously depends on age as well) so let's look at users over 21 and see how many of them are college grads
```

```{r}
ofAge = c("(11) Respondent is 22 or 23 years old", "(12) Respondent is 24 or 25 years old", "(13) Respondent is between 26 and 29 years old", "(14) Respondent is between 30 and 34 years old", "(15) Respondent is between 35 and 49 years old", "(16) Respondent is between 50 and 64 years old", "(17) Respondent is 65 years old or older")
drug_study_demographic_adults <- drug_study_demographic[(drug_study_demographic$AGE2 %in% ofAge), ]
summary(drug_study_demographic_adults$EDUCCAT2)
```
```{r}
ggplot(drug_study_demographic_adults, mapping=aes(EDUCCAT2)) +
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5)) +
  xlab("Education Level") +
  ggtitle("Education Breakdown of Oxycontin-using Adults") + 
  geom_bar()


# We see that 15.3% of Oxycontin using adults have an education of less than high school and 17.7% have a college degree.   Interesting that the lowest education tier has an even lower usage rate.  Remaining 67% either high school graduates or some college.
```


```{r}
ggplot(drug_study_demographic, mapping=aes(NEWRACE2)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Race breakdown of Oxycontin Users") + 
  geom_bar()

ggplot(drug_study, mapping=aes(NEWRACE2)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Race breakdown of all survey participants") + 
  geom_bar()

# Race variable not esp useful since even in original study, people predominantly nonhispanic whites and this is even more true in the subset of oxycontin users
# we lose some number of black and hispanic people, which implies that maybe these groups dont do oxy as much?
```

```{r}
# Dataset of all painkiller medications
ANLFLAG	PAIN RELIEVERS - EVER USED
ANLYR	PAIN RELIEVERS - PAST YEAR USE
ANLMON	PAIN RELIEVERS - PAST MONTH USE
DARVTYLC - EVER USED DARVOCET, DARVON, OR TYLENOL W/ CODEINE
PERCTYLX - EVER USED PERCOCET, PERCODAN, OR TYLOX
VICOLOR	- EVER USED VICODIN, LORTAB, OR LORCET
ANLCARD	- EVER USED PAIN RELIEVER BELOW RED LINE ON CARD A
CODEINE	- EVER USED CODEINE NONMEDICALLY
DEMEROL	- EVER USED DEMEROL NONMEDICALLY
DILAUD	- EVER USED DILAUDID NONMEDICALLY
FIORICET	- EVER USED FIORICET NONMEDICALLY
FIORINAL	- EVER USED FIORINAL NONMEDICALLY
HYDROCOD -	EVER USED HYDROCODONE NONMEDICALLY
METHDON	- EVER USED METHADONE NONMEDICALLY
MORPHINE	- EVER USED MORPHINE NONMEDICALLY
OXYCONTN	- EVER USED OXYCONTIN NONMEDICALLY
PHENCOD	- EVER USED PHENAPHEN WITH CODEINE NONMEDICALLY
PROPOXY	- EVER USED PROPOXYPHENE NONMEDICALLY
SK65A	- EVER USED SK65 NONMEDICALLY
STADOL	- EVER USED STADOL NONMEDICALLY
TALACEN	- EVER USED TALACEN NONMEDICALLY
TALWIN	- EVER USED TALWIN NONMEDICALLY
TALWINNX -	EVER USED TALWINNX NONMEDICALLY
TRAMADOL -	EVER USED TRAMADOL NONMEDICALLY
ULTRAM - EVER USED ULTRAM NONMEDICALLY
ANLNOLST - EVER USED ANY OTHER PAIN RELIEVER NONMEDICALLY
ANALAGE - AGE WHEN FIRST USED PAIN RELIEVERS NONMEDICALLY
OXYCAGE	- AGE WHEN FIRST USED OXYCONTIN NONMEDICALLY
OXYCYFU	- YEAR OF FIRST OXYCONTIN USE - RECODE
OXYCMFU	- MONTH OF FIRST OXYCONTIN USE - RECODE
OXYCREC -	TIME SINCE LAST USED OXYCONTIN NONMEDICALLY
OXYYRTOT	- TOTAL NUM DAYS USED OXYCONTIN PAST 12 MONTHS
OXTOTFG	- TRIMMING INDICATOR FOR OXYYRTOT
OXFQFLG	- TRIMMED OXYYRTOT IF R USED < 12 MOS
OXBSTWAY	- EASIEST WAY TO TELL US NUM DAYS USED OXYCONTIN
OXDAYPYR	- NUM DAYS USED OXYCONTIN 'NM' PAST 12 MONTHS
OXDAYPMO	- NUM DAYS PER MO USED OXYCONTIN 'NM' PAST 12 MOS
OXDAYPWK	- NUM DAYS PER WK USED OXYCONTIN 'NM' PAST 12 MOS
IRANLFY	- PAIN RELIEVER FREQ PAST YEAR - IMPUTATION REVISED
IIANLFY	- PAIN RELIEVER FREQ PAST YEAR - IMP INDICATOR
II2ANLFY	- PAIN RELIEVER FREQ PAST YR-DETAILED IMP INDICATOR
```

```{r}
summary(drug_study_sub$OXDAYPMO)
summary(drug_study_sub$OXDAYPYR)
summary(drug_study_sub$OXDAUPWK)
length(drug_study_sub)

ggplot(data = drug_study_sub, mapping = aes(OXDAYPYR)) + 
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,60,5)) + 
  xlim(0, 60)
```
```{r}
summary(drug_study_sub$ANLEVER)

ggplot(data = drug_study_sub, mapping = aes(ANALAGE)) + 
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks=seq(0,60,5)) + 
  xlim(0, 60)

ggplot(data = drug_study_sub, mapping = aes(ANLYRTOT)) + 
  geom_histogram(binwidth = 1) 

```

```{r}
# Proportion of opioid users in data
summary(drug_study$ANLEVER)
print(8094/nrow(drug_study))
dim((drug_study))
```



## STARTING FRESH HERE GOING BASED ON ANALYSIS PLAN ##
```{r}
load("35509-0001-Data.rda")
drug_study <- da35509.0001
```


```{r}
# ANLEVER : EVER USED PAIN RELIEVERS NONMEDICALLY
opioid_users <- drug_study[!is.na(drug_study$ANLEVER),]
cat('Percentage of all survey participants who have used prescription pain relievers nonmedically')
cat('\n')
cat(nrow(opioid_users)/nrow(drug_study)*100)
cat('%')
```


```{r}
# DATA CLEANING (maybe separate into another script eventually)

# SEX VARIABLE
opioid_users$Sex <- ifelse(opioid_users$IRSEX == "(1) Male","Male","Female")
opioid_users$Sex <- as.factor(opioid_users$Sex)

# INCOME VARIABLE
opioid_users$INCOME <- revalue(opioid_users$INCOME, c("(1) Less than $20,000"="<$20,000", "(2) $20,000 - $49,999"="$20,000 - $49,999", "(3) $50,000 - $74,999"="$50,000 - $74,999", "(4) $75,000 or More"=">$75,000"))
opioid_users$Income_Brackets <- as.factor(opioid_users$INCOME)
opioid_users$Income <- fct_relevel(opioid_users$Income_Brackets,">$75,000",after=3)
```

```{r}
# ANALAGE : AGE WHEN FIRST USED PAIN RELIEVERS NONMEDICALLY

summary(opioid_users$ANALAGE)
# We see that the lowest age of recorded non-medical opioid use is 1. Obviously, it is impossible that young children purposefully make decisions to misuse opioid, so we will ignore ages below 12 in our analysis of age groups. This is also more logical since it is the youngest age of survey participants, meaning the US Dept of Health deems them of approporiate age to question them about drug and alcohol use. This reduces our subset from 8094 to 7797, removing nearly 300 rows. 

opioid_users_above_12 <- opioid_users[opioid_users$ANALAGE >= 12.0,]

# Histogram and boxplot of first age of non-medical opioid use
p = ggplot(data = opioid_users_above_12, mapping = aes(ANALAGE)) + 
  geom_histogram(binwidth = 4) + 
  labs(title = "Age First Used Opioid", x = "Age", y = "Count") + 
  scale_x_continuous(breaks=seq(10,60,4)) 
show(p)


data <- layer_data(p, 1)
lower <- data$xmin
upper <- data$xmax
counts <- data$y

cat('\n')
cat(' Ages       Count of first opioid use in this age range')
cat('\n')
for (i in c(1:length(counts))){
  # justify options
  cat(sprintf(" %s - %s:   %s \n", toString(lower[i]), toString(upper[i]), toString(counts[i])))
}

# We see most common age group for trying prescription pain relievers non-medically is 14-18. The next most common is 18-22, and the third most common is 10-14. Interestingly enough, we see the highest initial use in teens and college-aged young adults. Rates seem to taper off more or less continuously as age increases. This raises an interesting find in that perhaps the biggest start to opioid misuse and addiction is not from chronic physical illnesses (found mostly in adults)?
```

```{r}
ggplot(data = opioid_users, mapping = aes(ANLYRTOT)) + 
  geom_histogram(binwidth = 10) + 
  labs(title = "Total Days Using Non-Medical Pain Reliever in Past Year", x = "Number of Days", y = "Count") + 
  scale_x_continuous(breaks=seq(0,365,20))

# To be consistent with many previous opioid investigations, we define frequent users as those with 100 or more days of nonmedical opioid use in the past year. Highly frequent users are those with 200 or more days of nonmedical use.

opioid_users <- opioid_users %>% mutate(
  frequency = case_when(
    opioid_users$ANLYRTOT < 100                  ~ 'infrequent',
    opioid_users$ANLYRTOT >= 200                   ~ 'highly frequent',
    TRUE                              ~ 'frequent'
  )
)

opioid_users$frequency

freq_opioid_users <-  opioid_users[opioid_users$frequency == 'frequent',]
highly_freq_opioid_users <-  freq_opioid_users[opioid_users$frequency == 'highly frequent',]
infreq_opioid_users <- opioid_users[opioid_users$frequency == 'infrequent',]
nrow(freq_opioid_users)
nrow(highly_freq_opioid_users)
nrow(infreq_opioid_users)


# We see 5658 frequent opioid users with 100+ days of use a year.  We see 5379 highly frequent opioid users with 200+ days of use a year.
```

```{r}
# Let's check current ages of frequent and highly frequent users (and pray they're not kids!!)

opioid_users$CATAG7 = revalue(opioid_users$CATAG7, c("(1) 12-13 Years Old"="12-13", "(2) 14-15 Years Old"="14-15", "(3) 16-17 Years Old"="16-17", "(4) 18-20 Years Old"="18-20", "(5) 21-25 Years Old"="21-25", "(6) 26-34 Years Old"="26-34", "(7) 35 or Older"="35+"))

opioid_users$frequency <- factor(opioid_users$frequency, levels = c("highly frequent", "frequent", "infrequent")) # same as below comment, would ideally want legend to be in opposite order
opioid_users$CATAG7 <- factor(opioid_users$CATAG7, levels = c("35+", "26-34", "21-25", "18-20", "16-17", "14-15", "12-13")) # have to factor them backwards to get it in lowest to highest up to down in graph, weird.... fix for this?

ggplot(opioid_users, aes(CATAG7)) + 
  geom_bar(aes(fill=frequency), position="fill") + 
  labs(title="Opioid Use Frequency Based on Age Group",
        x="Age Bracket",
        y="Proportion",
        fill='Frequency of Use') +
  coord_flip()

# Looks like across most age group, we have similarly low proportions of highly frequent users using opioids 200+ days a year
# Interesting that from age 14 onwards, we have increasing proportion of frequent users -> 35+ group has greatest group of "frequent" users

```

```{r}
summary(opioid_users$INCOME)
```


```{r}
p1 <- mosaic(Income ~ Sex, 
       direction=c('v', 'h'), 
       labeling_args = list(rot_labels = c(0, 0, 0, 0), 
                            offset_varnames = c(left = 6), 
                            offset_labels = c(left = 2.6)),
       gp = grid::gpar(fill=c('#CCCCFF', '#CC99FF', '#9966CC', '#663399')),
       main = "Sex and Income of Opioid Users",
       opioid_users)

p2 <- mosaic(Income ~ Sex, 
       direction=c('v','h'), 
       labeling_args = list(rot_labels = c(0, 0, 0, 0), 
                            offset_varnames = c(left = 6), 
                            offset_labels = c(left = 2.6)),
       gp = grid::gpar(fill=c('#CCCCFF', '#CC99FF', '#9966CC', '#663399')),
       main = "Sex and Income of Frequent Opioid Users",
       freq_opioid_users)

p3 <- mosaic(Income ~ Sex, 
       direction=c('v','h'), 
       labeling_args = list(rot_labels = c(0, 0, 0, 0), 
                            offset_varnames = c(left = 6), 
                            offset_labels = c(left = 2.6)),
       gp = grid::gpar(fill=c('#CCCCFF', '#CC99FF', '#9966CC', '#663399')),
       main = "Sex and Income of Highly Frequent Opioid Users",
       highly_freq_opioid_users)

summary(opioid_users$Sex)
summary(freq_opioid_users$Sex)
summary(highly_freq_opioid_users$Sex)

# We see a pretty believable / expected trend. Users who do opioids frequently and hihgly frequently seem to be poorer - with salaries under $50000. It's interesting that across all types of users, the least popular income bracket for users is $50-75k.  When looking at all opioid users, we see a nearly equal number of men and women, but as we examine the frequent and the highly frequent users, a larger percentage of the users become male.  

# All opioid users: 50.4% men, 49.6% women
# Frequent users: 54% men, 46% women
# Highly frequent users: 56.6% men, 43.4% women
```

```{r}
summary(opioid_users$BOOKED)
summary(freq_opioid_users$BOOKED)
summary(highly_freq_opioid_users$BOOKED)
summary(infreq_opioid_users$BOOKED)

opioid_users$BOOKED = revalue(opioid_users$BOOKED, c("(1) Yes"="Yes", "(2) No"="No", "(3) Yes LOGICALLY ASSIGNED"="Yes"))

# Histogram and boxplot of first age of non-medical opioid use
p = ggplot(data = opioid_users[!is.na(opioid_users$BOOKED),], mapping = aes(BOOKED)) + 
  geom_bar(aes(y = ..prop.., group = 1)) + 
  facet_wrap(~frequency) +
  labs(title = "Ever Been Arrested and Booked for Breaking Law", x = "Been Booked", y = "Proportion")  
show(p)

# Interestingly enough, we see that in highly frequent opioid users, there is a nearly equal rate of people who have been arrested vs those who have not been. For infrequent and infrequent users, we see that between 65-75% of people have not been arrested and booked, but it's about 50% for highly frequent users.
```


