---
title: "Final Project: Exploring the National Survey on Drug Use and Health "
author: "Suman Tripathy, Amanda Steigman"
date: "11/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(vcd)
library(forcats)
library(scales)
library(dplyr)
library(plyr)
```

## I. Introduction

Over the last few years, the opioid crisis in America has been worsening rapidly and is perhaps finally gaining the public and media awareness it needs The topic is both concerning and fascinating. When people think of drugs, the most obvious, widespread choices are alcohol and marijuana. The flashier ones that may come to mind afterwards include cocaine, LSD, ecstasy, and so on. 

Opioids, however, are getting more and more common. The National Institute on Drug Abuse found in January 2019 that "more than 130 people in the United States die after overdoing on opioids" every day. Opioids are most commonly prescription pain relievers but also include heroin and synthetic opioids such as fentanyl. The Centers for Disease Control and Prevention has released an estimate that opioid misuse in the US costs $78.5 billion a year in terms of healthcare costs, lost productivity, rehab treatments, and criminal justice activities.

An alarming number of doctors have been caught for inappropriate opiod prescription. Moreover, 21 to 29% of chronic pain patients have been found to misuse their prescribed opioids.  8 to 12% may develop an opioid use disorder, and 4 to 6% transition from an opioid prescripton to heroin use. Given these worrisome figures, we chose to explore data regarding the United States drug use and abuse. We are most interested in questions such as:

  - What are the interesting relationships between opioid abuse and different demographics?
  - What particular difficulties do youth who abuse Oxycontin face?
  - Is there are strong relationship between Oxycontin abuse and crime? What interesting depth can income and education add to this relationship?
  - What trends do we see between opioid abuse and other substance abuse?
  - We know thereis a relationship between physical illness and opioid abuse, bu what about mental illness?
  - 

## II. Data Sources

Our data source is the National Survey on Drug Use and Health from 2013. The primary investigators were the United States Department of Health and Human Services, the Substance Abuse and Mental Health Services Administration, and the Center for Behavioral Health Statistics and Quality. This survey has been conducted perioidically since 1971 and has transitioned from a traditional paper-pencil method to a computer-assisted interviewing method. It combines computer-assisted personal interviewing and computer-assisted self-interviewing. It is a highly private and confidential system in order to encourage participant honesty regarding these sensitive behaviors.

The demographic population is "the civilian, noninstituitionalized population of the United States ... who were 12 years of age or older at the time of the survey." Since 2002, NSDUH respondents have been incentivized with a $30 reward for taking the survey, and an improvement in the survey response rate was noted afterwards. This increase in response rate may also be tied to better public awareness about these critical issues.  ** SHOULD TRY TO LOOK FOR MORE CONCRETE INFO ON HOW THE SURVEY IS SENT OUT **

source: https://www.icpsr.umich.edu/icpsrweb/NAHDAP/studies/35509/documentation#

The dataset itself contains a myriad of informaition about the use of drugs, alcohol, and tobacco. It also covers mental and physical illnesses, population demographics, criminal activities, and more.  The target demographic is members of US households, age 12 and older.

As we are working with survey data, we will make sure to be aware of all the possible challenges that may come with this (for example, making sure that "missing" values are actually "missing" and are not logically "no." We are checking this by going back to earlier survey sections to see how participants earlier responses may have caused parts of the survey to be skipped).

## III. Data Transformation

We imported our data as a .rda file, which added a new challenge because loading and accessing the data was different than with the previous file types we have worked with. 

## IV. Missing Values

## V. Results

## VI. Interactive Component

## VII. Conclusion
